---
title: "'Catch' ne peut pas apparaître après 'Finally' dans une instruction 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 13b8ce225fe487b0c597a6fe81983543e5af535e
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/18/2019
ms.locfileid: "59311329"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' ne peut pas apparaître après 'Finally' dans une instruction 'Try'
Une instruction `Catch` apparaît dans le code après `Finally` qui termine un bloc d’instruction `Try` . `Catch` doit apparaître dans un bloc d’instruction `Try...Catch...Finally` .  
  
 **ID d’erreur :** BC30379  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1. Déplacez l’instruction `Catch` vers un emplacement plus approprié dans le code.  
  
## <a name="see-also"></a>Voir aussi

- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
