---
title: "'Exit Try' ne peut apparaître qu’à l’intérieur d’une instruction 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 7e7d1a1a9025c2d708d7e5027fd9bcbb4270e60b
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62027457"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' ne peut apparaître qu’à l’intérieur d’une instruction 'Try'
`Exit Try` ne peut figurer qu’à l’intérieur d’une instruction de bloc `Try` . Soit vous avez une instruction `Exit Try` redondante, soit votre instruction `Exit Try` apparaît en dehors des limites de son bloc `Try` correspondant.  
  
 **ID d’erreur :** BC30393  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1. Recherchez et supprimez l’instruction `Exit Try` inutile.  
  
2. Déplacer le `Exit Try` instruction à l’emplacement approprié dans votre code.  
  
## <a name="see-also"></a>Voir aussi

- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
