---
title: Bloc 'Catch' jamais atteint ; <exception> géré au-dessus dans la même instruction 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: HT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62003663"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloc 'Catch' jamais atteint ; \<exception > géré au-dessus dans la même instruction 'Try'
Un bloc `Catch` du code n’est pas accessible, car il est géré dans un bloc `Try` précédent.  
  
Par défaut, ce message est un avertissement. Pour plus d’informations sur le masquage des avertissements ou le traitement des avertissements en tant qu’erreurs, consultez [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID d’erreur :** BC42031  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
- Supprimez l’instruction redondante.  
  
## <a name="see-also"></a>Voir aussi

- [Comment utiliser le bloc try/catch pour intercepter des exceptions](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Utilisation de gestionnaires filtrés par l'utilisateur](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
